services:
  - type: web
    name: flowserve-backend
    env: node
    buildCommand: npm install && npm run db:generate
    startCommand: npm run production
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_KEY
        generateValue: true
      - key: BCRYPT_SALT_ROUNDS
        value: 12
  - type: pserv
    name: flowserve-db
    env: postgresql
    plan: free